WikiSeries/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :series
  root 'home#index'
  get 'home' => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

WikiSeries/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WikiSeries/app/models/series.rb
class Series < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates  :name, :image, :creator, :year, presence:true
end

WikiSeries/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

WikiSeries/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

WikiSeries/app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all;
    authorize @users
  end
end

WikiSeries/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @series = Series.limit(4).order("RANDOM()")
  end
end

WikiSeries/app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :not_user, except: [:index, :show]
  before_action :set_series, only: [:show, :edit, :update, :destroy]
  before_action :not_admin, only: [:destroy]

  # GET /series
  # GET /series.json
  def index
    @q = Series.ransack(params[:q])
    @series = @q.result
  end

  def not_admin
      redirect_to series_path unless current_user.admin?
  end

  def not_user
      redirect_to root_path if current_user.blank?
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :creator, :gender, :year, :image)
    end

end

WikiSeries/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário apagado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

WikiSeries/app/helpers/application_helper.rb
module ApplicationHelper
end

WikiSeries/app/helpers/control_users_helper.rb
module ControlUsersHelper
end

WikiSeries/app/helpers/home_helper.rb
module HomeHelper
end

WikiSeries/app/helpers/series_helper.rb
module SeriesHelper
end

WikiSeries/app/helpers/users_helper.rb
module UsersHelper
end

WikiSeries/app/views/home/index.html.erb
<div class="conteiner1">
  <div class="conteiner2">
    <div class="textconteiner2">


      <div class="row">
        <% @series.each do |serie|%>
        <div class="col-xs-6 col-md-3">
          <a href="<%= series_path serie %>" class="thumbnail">
            <%= image_tag serie.image.url%>
            <div class="caption">
            </div>
          </a>
        </div>
        <%end%>
      </div>


    </div>
  </div>
</div>

WikiSeries/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title><%= content_for?(:title) ? yield(:title) : "WikiSeries" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>

  <%if user_signed_in? %>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar">
	            <li><%= link_to "Séries", series_index_path %></li>
	        </ul>

          <a href="/home">
            <ul class="nav navbar-nav navbar-center"></ul>
          </a>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
	        </ul>

          

          <div id="emailName">
          <ul class="nav navbar-nav navbar-right">
            <a href="/users/edit"><li><%= current_user.email %></li></a>
	        </ul>
        </div>


        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>

  <% else %>

  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">

          <ul class="nav navbar-nav navbar">
              <li><%= link_to "Séries", series_index_path %></li>
          </ul>

            <a href="/home">
            <ul class="nav navbar-nav navbar-center-out"></ul>
            </a>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Entrar", new_user_session_path %></li>
            <li><%= link_to "Cadastrar", new_user_registration_path %></li>

	        </ul>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
  <%end%>
</html>

WikiSeries/app/views/series/_form.html.erb
<%= form_for @series, :html => { :class => "form-horizontal series" , multipart: true} do |f| %>

<% if @series.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@series.errors.count, "Espaço(os) em branco") %></h3>
    </div>
  </div>
<% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :creator, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :creator, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Gender", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :gender,['Ação','Terror','Ficção Científica','Romance','Comédia'] %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Criar Série', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                series_index_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

WikiSeries/app/views/series/_form2.html.erb
<%= form_for @series, :html => { :class => "form-horizontal series" , multipart: true} do |f| %>

<% if @series.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@series.errors.count, "Espaço(os) em branco") %></h3>
    </div>
  </div>
<% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :creator, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :creator, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Gender", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :gender,['Ação','Terror','Ficção Científica','Romance','Comédia'] %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Editar Série', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                series_index_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

WikiSeries/app/views/series/edit.html.erb
<div class="backPages">
  <div class="backInside">
<%- model_class = Series -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form2' %>
  </div>
</div>

WikiSeries/app/views/series/index.html.erb
<%- model_class = Series -%>
<div class="backEdit">
  <div class="backEditIn">
<%- model_class = Series -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= sort_link(@q, :name) %></th>
      <th><%= model_class.human_attribute_name(:creator) %></th>
      <th><%= sort_link(@q, :year) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= link_to series.id, series_path(series) %></td>
        <td><%= series.name %></td>
        <td><%= series.creator %></td>
        <td><%= series.year %></td>
        <td><%= series.gender %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      series_path(series), :class => 'btn btn-default btn-xs' %>
          <%if current_user.present?%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_series_path(series), :class => 'btn btn-default btn-xs' %>
          <%if current_user.admin?%>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      series_path(series),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <%end%>
          <%end%>
        </td>
      </tr>
        <% end %>
  </tbody>
</table>
<%if current_user.present?%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_series_path,
            :class => 'btn btn-primary' %>
<% end %>
  <div id="search">
    <%= search_form_for @q do |f| %>
      <%= f.search_field(:name_cont, placeholder: 'Nome') %>
      <%= f.search_field(:gender_cont, placeholder: 'Gênero') %>
      <%= f.submit 'Buscar' %>
  </div>
    <% end %>
  </div>
</div>

WikiSeries/app/views/series/new.html.erb
<div class="backEdit">
  <div class="backEditIn">
  <%- model_class = Series -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
  </div>
</div>

WikiSeries/app/views/series/show.html.erb
<div class="backPages">
  <div class="backInside">
<%- model_class = Series -%>
<div class="page-header">
  <h1><%= @series.name %> </h1>
</div>

<dl class="dl-horizontal">

  <div id="image"<dd><%= image_tag @series.image.url %></dd></div>
  <div id="descriptions"><dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @series.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:creator) %>:</strong></dt>
  <dd><%= @series.creator %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @series.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @series.year %></dd>
</div>
</dl>

<div id="buttonShow">
<%= link_to t('.back', :default => t("helpers.links.back")),
              series_index_path, :class => 'btn btn-default'  %>
<%if current_user.present?%>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_series_path(@series), :class => 'btn btn-default' %>
<%if current_user.admin?%>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              series_path(@series),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
              :class => 'btn btn-danger' %>
</div>
<%end%>
<%end%>
  </div>
</div>

WikiSeries/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

WikiSeries/app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

WikiSeries/app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

WikiSeries/app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

WikiSeries/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Não possuo cadastro", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueci minha senha", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

WikiSeries/app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
              :class => 'btn btn-danger' %>